import traceback

from copy import deepcopy

from typing import Any
from typing import List
from typing import Tuple
from typing import Callable

from .config import LOG
from .config import LoggingBehavior
from .edge import Edge
from .job import Job

BEGIN = 'Start'


class Node(LoggingBehavior):
    """Represents a node in an ETL (Extract, Transform, Load) graph.
    Each node contains a job function that performs a specific task in 
    the ETL process. The node manages the inputs, outputs, and errors
    associated with the job function, and provides properties to track 
    the progress and status of the node.

    Parameters
    ----------
    graph : Graph
        The ETL Graph object that this node belongs to.
    job_function : Callable
        The job function that this node represents.
    inputs_from : str
        The name of the node that this node receives input from.
    designation : str
        The designation of the node.
    first : bool, optional
        Whether this node is the first node in the graph,
        by default True.
    last : bool, optional
        Whether this node is the last node in the graph,
        by default False.
    """

    name: str
    """Name of the node. Same as name of given job function."""

    job: Job
    """Job function that this node represents."""

    inputs_from: str
    """Name of the node that this node receives input from."""

    first: bool
    """Whether this node is the first node in the graph."""

    last: bool
    """Whether this node is the last node in the graph."""

    repr_len: int = 25
    """Length of the string representation of the node."""

    n_jobs_todo: int
    """Number of available inputs when starting loop."""

    count_in: int
    """Number of inputs received so far."""
    
    count_out = 0
    """Number of outputs generated so far."""
    
    errors = []
    """Collection of errors encountered during job execution."""

    _inputs: List[Edge] = []
    """List of input edges for the node."""
    
    _inputs_idx: int = 0
    """Index of the current input edge."""
    
    outputs = []
    """List of outputs generated by the job function."""

    additional_info: str = ''
    """"Additional information to be displayed in the node."""

    last_output: Tuple[Any, ...]
    """Last output generated by the job function."""

    is_first_job: bool = False
    """Whether current job is the first job for this node."""

    is_last_job: bool = False
    """Whether current job is the last job for this node."""
    
    def __init__(
            self,
            graph,
            job_function: Callable,
            inputs_from: str,
            designation: str = '',
            first: bool = True,
            last: bool = False
            ) -> None:
        self.graph = graph
        self.job = Job(job_function, designation)
        self.name = self.job.name
        self.inputs_from = inputs_from
        self.first = first
        self.last = last
        self.preset()

    @property
    def count_err(self) -> int:
        """Get amount of occured errors during job execution (read-only)."""
        return len(self.errors)
    
    @property
    def inputs(self) -> Edge:
        """get inputs by stored index for given input edge
        
        set inputs of given edge list by getting the index of a non 
        empty deque in the edge list"""
        if not self._inputs:
            return Edge()
        return self._inputs[self._inputs_idx]
    @inputs.setter
    def inputs(self, edges: List[Edge]) -> None:
        self._inputs = edges
        self.log(f'Inputs changed, n inputs = {len(edges)}', LOG.TRACE)
        if self._inputs:
            for idx, inputs in enumerate(self._inputs):
                if len(inputs): 
                    self._inputs_idx = idx
                    break
    
    @property
    def n_inputs(self) -> int:
        """Get amount of available inputs (read-only)."""
        if type(self.inputs) is tuple and self.inputs:
            return 1
        
        return len(self.inputs)
    
    @property
    def n_outputs(self) -> int:
        """Get amount of available outputs (read-only)."""
        if type(self.outputs) is tuple and self.outputs:
            return 1
        
        return len(self.outputs)
    
    @property
    def no_outputs(self) -> bool:
        """True if no output is generated (read-only)."""
        if not self.outputs:
            return True
        
        return not any([bool(len(edge)) for edge in self.outputs])
    
    @property
    def progress(self) -> float:
        """Get progress of jobs done as {p | 0 < p <= 1} (read-only)."""
        if self.n_jobs_todo == 0:
            p = 0.5
        else:
            p = self.count_in/self.n_jobs_todo
        return max(0.01, min(p, 100))
    
    def preset(self) -> None:
        """set counters to 0 and empty errors, inputs and outputs"""
        self.n_jobs_todo = 0
        self.count_in = 0
        self.count_out = 0
        self.errors = []
        self._inputs: List[Edge] = []
        self._inputs_idx: int = 0
        self.outputs = []
        self.additional_info = ''

    def loop(self, edges_in: List[Edge], edges_out: List[Edge]) -> None:
        """Start loop over the jobs done by the job_function"""
        self.log(
            f'{self.n_inputs} jobs for node "{self.job.designation}"',
            LOG.INFO)
        self.inputs = edges_in
        self.outputs = edges_out
        self.n_jobs_todo = deepcopy(self.n_inputs)
        self.job.interrupt = False
        for job_count in range(1, self.n_jobs_todo + 1):
            self.is_first_job = job_count == 1
            self.is_last_job = job_count == self.n_jobs_todo
            self.do_job(self.inputs.popleft())
    
    def do_job(self, job_data: Tuple[Any, ...]) -> None:
        """Generate outputs done by the job_function by giving a new job 
        as arguments for generetor."""
        try:
            if self.graph.cancel:
                self.log('Skip job because of graph cancel', LOG.TRACE)
                return
            
            for output in self.job(*job_data):
                if self.graph.cancel:
                    self.job.interrupt = True
                    break
                
                output = self._ensure_tuple_(output)
                self._store_output_(output)
        
        except KeyboardInterrupt as e:
            self.graph.cancel = True
            self.log(f'{self} interrupted because: {e}', LOG.INFO)
        
        except Exception as e:
            self.log(
                f'Cached error = {e}\nError occured @ node{repr(self)}',
                LOG.WARNING)
            if LOG.TRACEBACK:
                self.log(f'{traceback.format_exc()}', LOG.ERROR)
            self.errors.append(e)
        
        finally:
            self.count_in += 1
    
    @staticmethod
    def _ensure_tuple_(output) -> Tuple[Any, ...]:
        """If a single value is returned, wrap it in a tuple"""
        return output if type(output) is tuple else (output, )
    
    def _store_output_(self, output: Tuple[Any, ...]) -> None:
        """Store output in all output queues"""
        self.last_output = output
        for q in self.outputs:
            q.append(output)
        self.log(f'Stored output @ node {self}' , LOG.TRACE)
        self.count_out += 1
    
    def __len__(self) -> int:
        if self.first:
            inputs = self.inputs
            if not type(inputs) is tuple: 
                inputs = (inputs, )
            try:
                length = len(inputs[0])
            except TypeError:
                length = 0
        else:
            length = self.n_inputs
        return length

    def __str__(self) -> str:
        return f'{self.name} ({self.inputs_from})'

    def __repr__(self) -> str:
        name = self.name.ljust(self.repr_len+1)
        r = f'  |-{name}|{self.count_in: 4}|{self.count_out: 4}|{self.count_err: 4}|'
        if self.first: 
            r = (f'{self.inputs_from.ljust(self.repr_len+6)}'
                + ' '.join([s.ljust(4) for s in ('in', 'out', 'err')])
                + f'\n{r}')
        return r


__all__ = ['BEGIN', 'Node']
